### PR TITLE
builder: add internal versions, which are needed for the Patch API

### PR DESCRIPTION
**Pull request by nicks**
Hello @milas,

Please review the following commits I made in branch nicks/patch:

f599f99fa1b85b918eefc56efe3b47a9dcd56390 (2021-08-17 14:39:34 -0400)
builder: add internal versions, which are needed for the Patch API

Code review reminders, by giving a LGTM you attest that:

* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

### CODE REVIEW

**Comment by nicks** [comment]
I was trying to do some stuff with kubectl patch, but it wasn't working properly. this fixes it.

TBH, I don't deeply understand the role of the __internal version in kubernetes. as far as i can tell (from reading various issue threads), it started out as a kludge to help convert between versions of objects, but lots of tools ended up relying on it being there.

**Comment by milas** [comment]
Yeah my understanding is that `__internal` is the "canonical" version that other versions are supposed to (transitively?) convert to, so I think it might still apply to us if e.g. we migrate to v1 APIs and want to transparently convert v1alpha1 at the same time.

That said, still surprising that it's explicitly need for patch support 😛

**Review by milas — APPROVED** [review]

**Comment by milas** [comment]
Also excited for patch support, I tried it once early on and ran away fast when it blew up. 

FYI this might be helpful if you haven't already seen it: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#CreateOrPatch

**Comment by nicks** [comment]
@milas yes! I first learned about that from an earlier message you posted

I think the week you were on vacay i spent some time poking around at it and wrote up this ticket https://app.clubhouse.io/windmill/story/12387/use-createorupdate-createorpatch-to-do-updates

but didn't come up with a plan for how to use it in our code

**Pull request merged**
